apiVersion: v2
name: schema-server
description: Serves JSON schema provided by Giant Swarm
home: https://github.com/giantswarm/schema-server
icon: https://s.giantswarm.io/app-icons/json-schema/1/light.svg
sources:
  - https://github.com/giantswarm/schema-server
version: 0.2.0
appVersion: 0.0.1
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.team: honeybadger
  io.giantswarm.ui.logo: https://s.giantswarm.io/app-icons/json-schema/1/logo_light.svg
