{{- if .Values.route.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-tls-redirect" ((include "name" .) | trunc 50 | trimSuffix "-") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.hostnames }}
  - {{ . }}
  {{- end }}
  parentRefs:
  {{- .Values.route.parentRefs.redirect | toYaml | nindent 2 }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.hostnames }}
  - {{ . }}
  {{- end }}
  parentRefs:
  {{- .Values.route.parentRefs.https | toYaml | nindent 2 }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.name }}
      port: 8000
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
